# Generated by Django 5.1.3 on 2024-11-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_discountcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonalsale',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
