# Generated by Django 5.1.3 on 2024-11-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_alter_product_farmer_discount_coupon'),
        ('product', '0005_remove_coupon_discount_value_and_more'),
    ]

    operations = [
    ]
