# Generated by Django 5.1.1 on 2024-11-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_faqs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQs',
        ),
    ]
