# Generated by Django 5.1.3 on 2024-11-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_guest_address_order_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal')], default='PayPal', max_length=50),
        ),
    ]
