# Generated by Django 5.1.3 on 2024-11-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
    ]
